sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

branches:
  except:
    - gh-pages
    - /^v\d/

script:
  - python setup.py test

notifications:
  email:
    on_success: never
    on_failure: always
